import { defineConfig } from "tsup";

export default defineConfig({
	entry: {
		index: "src/index.ts",
		adapter: "src/adapter.ts",
		"diagnostics-bundle": "src/diagnostics-bundle.ts",
		evaluation: "src/evaluation.ts",
		"evidence-cluster": "src/evidence-cluster.ts",
		"graph-contracts": "src/graph-contracts.ts",
		"graph-evolution": "src/graph-evolution.ts",
		"graph-lifecycle": "src/graph-lifecycle.ts",
		"graph-retrieval": "src/graph-retrieval.ts",
		governance: "src/governance.ts",
		persistence: "src/persistence.ts",
		pipeline: "src/pipeline.ts",
		"reflect-planner": "src/reflect-planner.ts",
		"relation-graph": "src/relation-graph.ts",
		retrieval: "src/retrieval.ts",
		revision: "src/revision.ts",
		runtime: "src/runtime.ts",
		"semantic-draft": "src/semantic-draft.ts",
		shadow: "src/shadow.ts",
	},
	format: ["esm"],
	dts: true,
	sourcemap: false,
	clean: true,
	splitting: false,
	treeshake: true,
	external: ["react", "react-dom", "@tauri-apps/api", "better-sqlite3", "sqlite-vec"],
});
