import { defineConfig } from "tsup";

export default defineConfig({
	entry: {
		index: "src/index.ts",
		types: "src/types.ts",
		"memory/index": "src/memory/index.ts",
		"store/index": "src/store/index.ts",
		"audio/index": "src/audio/index.ts",
		"agent/index": "src/agent/index.ts",
		"agent/types": "src/agent/types.ts",
		"agent/registry": "src/agent/registry.ts",
		"agent/plugin": "src/agent/plugin.ts",
		"agent/native-cli/index": "src/agent/native-cli/index.ts",
		"agent/native-runner/index": "src/agent/native-runner/index.ts",
		"agent/runtime/index": "src/agent/runtime/index.ts",
		"agent/runtime/output-event-bus": "src/agent/runtime/output-event-bus.ts",
		"agent/supplemental-input/index": "src/agent/supplemental-input/index.ts",
		"agent/runtime-instructions/index": "src/agent/runtime-instructions/index.ts",
		"agent/image-gen/index": "src/agent/image-gen/index.ts",
		"agent/video-gen/index": "src/agent/video-gen/index.ts",
		"agent/sandbox/index": "src/agent/sandbox/index.ts",
		"agent/sandbox/types": "src/agent/sandbox/types.ts",
		"agent/sandbox/plugin": "src/agent/sandbox/plugin.ts",
		"agent/sandbox/registry": "src/agent/sandbox/registry.ts",
		"agent/sandbox/providers/native": "src/agent/sandbox/providers/native.ts",
		"agent/sandbox/providers/claude": "src/agent/sandbox/providers/claude.ts",
		"agent/sandbox/providers/vercel": "src/agent/sandbox/providers/vercel.ts",
		"agent/billing/index": "src/agent/billing/index.ts",
		"agent/billing/model-pricing": "src/agent/billing/model-pricing.ts",
		"agent/ai/index": "src/agent/ai/index.ts",
		"agent/compaction/index": "src/agent/compaction/index.ts",
		"agent/compaction/compaction": "src/agent/compaction/compaction.ts",
		"agent/compaction/compaction-client": "src/agent/compaction/compaction-client.ts",
		"context/index": "src/context/index.ts",
		"agent/model/index": "src/agent/model/index.ts",
		"agent/routing/index": "src/agent/routing/index.ts",
		// provider implementations live under providers/ in source
		"agent/providers/standalone": "src/agent/providers/standalone.ts",
		"agent/providers/standalone-plugin": "src/agent/providers/standalone.ts",
		"agent/providers/cli-process": "src/agent/providers/_internal/cli-process.ts",
		"agent/providers/prompt-context": "src/agent/providers/_internal/prompt-context.ts",
		"agent/providers/claude/cli-locations": "src/agent/providers/claude/cli-locations.ts",
		"agent/providers/codex/index": "src/agent/providers/codex/index.ts",
		"agent/providers/codex/command": "src/agent/providers/codex/command.ts",
		"agent/providers/codex/interrupt-marker": "src/agent/providers/codex/interrupt-marker.ts",
		"agent/providers/codex/metadata": "src/agent/providers/codex/metadata.ts",
		"agent/providers/codex/parser": "src/agent/providers/codex/parser.ts",
		"agent/providers/codex/runtime-preflight": "src/agent/providers/codex/runtime-preflight.ts",
		"agent/providers/codex/transport-status": "src/agent/providers/codex/transport-status.ts",
		"agent/providers/hermes/index": "src/agent/providers/hermes/index.ts",
		"agent/providers/hermes/command": "src/agent/providers/hermes/command.ts",
		"agent/providers/hermes/metadata": "src/agent/providers/hermes/metadata.ts",
		"agent/providers/openclaw/index": "src/agent/providers/openclaw/index.ts",
		"agent/providers/openclaw/command": "src/agent/providers/openclaw/command.ts",
		"agent/providers/openclaw/metadata": "src/agent/providers/openclaw/metadata.ts",
		"agent/providers/opencode/index": "src/agent/providers/opencode/index.ts",
		"agent/providers/opencode/command": "src/agent/providers/opencode/command.ts",
		"agent/providers/opencode/metadata": "src/agent/providers/opencode/metadata.ts",
		"agent/providers/opencode/parser": "src/agent/providers/opencode/parser.ts",
		"agent/providers/acp/agent": "src/agent/providers/acp/agent.ts",
		"agent/providers/acp/mapper": "src/agent/providers/acp/mapper.ts",
		"agent/providers/acp/stdio-client": "src/agent/providers/acp/stdio-client.ts",
		// native-agent lives at agent/native-agent/ (no providers/ equivalent)
		"agent/native-agent/native-runner": "src/agent/native-agent/native-runner.ts",
		"agent/native-agent/provider-env": "src/agent/native-agent/provider-env.ts",
		"agent/native-agent/register-provider": "src/agent/native-agent/register-provider.ts",
		"agent/native-agent/runtime-contract": "src/agent/native-agent/runtime-contract.ts",
		"agent/native-agent/runtime-preference": "src/agent/native-agent/runtime-preference.ts",
		"agent/native-agent/runtime-probe": "src/agent/native-agent/runtime-probe.ts",
	},
	format: ["esm"],
	dts: true,
	sourcemap: false,
	clean: true,
	splitting: false,
	treeshake: true,
	external: ["react", "react-dom", "@tauri-apps/api", "better-sqlite3", "sqlite-vec"],
});
